// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeDle5oVfVTglU3CTNoq9bHWzEShEhGw4',
    appId: '1:610728338505:android:b06b84c64d1b428e6d0b98',
    messagingSenderId: '610728338505',
    projectId: 'fleetfill',
    storageBucket: 'fleetfill.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzOqb62xNfrusLbmVBYEOoN3wpv8sxJwI',
    appId: '1:610728338505:ios:12ca02e39a33141b6d0b98',
    messagingSenderId: '610728338505',
    projectId: 'fleetfill',
    storageBucket: 'fleetfill.firebasestorage.app',
    iosBundleId: 'com.carbodex.fleetfill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjEeMlsmzHI9Sn6ibnIphpv7KsZDZTuS8',
    appId: '1:610728338505:web:89c5d3396925d1b16d0b98',
    messagingSenderId: '610728338505',
    projectId: 'fleetfill',
    authDomain: 'fleetfill.firebaseapp.com',
    storageBucket: 'fleetfill.firebasestorage.app',
    measurementId: 'G-CVHFD5N55F',
  );
}
